### ISSUE TITLE
conda installation in mac OS

### ISSUE THREAD

**Issue by xiuliren** [janelia-flyem/dvidutils#3]
Hi, I am trying to install this package in mac OS, but got an error of loading draco. 

I used the following command to install it.
```
mamba install -c conda-forge -c flyem-forge dvidutils
```

The errors are as follows:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jwu/code/pydvid/dvid/__init__.py", line 11, in <module>
    from .annotation import *
  File "/Users/jwu/code/pydvid/dvid/annotation.py", line 14, in <module>
    from dvidutils import LabelMapper
  File "/Users/jwu/opt/anaconda3/envs/cf/lib/python3.10/site-packages/dvidutils/__init__.py", line
 2, in <module>
    from . import _dvidutils as _dvidutils
ImportError: dlopen(/Users/jwu/opt/anaconda3/envs/cf/lib/python3.10/site-packages/dvidutils/_dvidu
tils.so, 0x0002): Library not loaded: @rpath/libdraco.1.dylib
  Referenced from: <E437E875-1F66-3445-AEC9-1C13F9011BE6> /Users/jwu/opt/anaconda3/envs/cf/lib/pyt
hon3.10/site-packages/dvidutils/_dvidutils.so
  Reason: tried: '/Users/jwu/opt/anaconda3/envs/cf/lib/python3.10/site-packages/dvidutils/../../..
/libdraco.1.dylib' (no such file), '/Users/jwu/opt/anaconda3/envs/cf/lib/python3.10/site-packages/
dvidutils/../../../libdraco.1.dylib' (no such file), '/Users/jwu/opt/anaconda3/envs/cf/bin/../lib/
libdraco.1.dylib' (no such file), '/Users/jwu/opt/anaconda3/envs/cf/bin/../lib/libdraco.1.dylib' (
no such file), '/usr/local/lib/libdraco.1.dylib' (no such file), '/usr/lib/libdraco.1.dylib' (no s
uch file, not in dyld cache)
```

any idea to fix it?

**Comment by xiuliren** [comment]
NVM, I fixed by a trick: directly copying the library from another environment!

```
(cf) ➜  ~ cp /Users/jwu/opt/anaconda3/envs/managed_neutu/lib/libdraco* /Users/jwu/opt/anaconda3/en
vs/cf/lib/
```
